dist: trusty
language: node_js
node_js:
- 10.13.0
cache:
  directories:
  - node_modules
addons:
  ssh_known_hosts:
  - 178.128.155.96
branches:
  only:
  - master
env:
  global:
  - REMOTEAPPDIR=/var/www/
  - REMOTEUSER=deploy
  - REMOTEHOST=178.128.155.96
  - PORT=80
install: yarn
script:
- yarn build
notifications:
  email: false
after_success:
- chmod 600 deploy-key && mv deploy-key ~/.ssh/id_rsa
- echo "deploy to 178.128.155.96"
- scp dist.tar.gz deploy@178.128.155.96:~/
- ssh deploy@178.128.155.96 'tar -xzvf ~/dist.tar.gz -C /var/www && cd /var/www &&
  pm2 stop all && npm i --production && npm run start &> /var/log/app.log'
before_install:
- openssl aes-256-cbc -K $encrypted_7b417e6d3d7a_key -iv $encrypted_7b417e6d3d7a_iv
  -in deploy-key.enc -out deploy-key -d
