dist: trusty
language: node_js
node_js:
- 10.13.0
cache:
  directories:
  - node_modules
addons:
  ssh_known_hosts:
  - 46.101.164.17
branches:
  only:
  - master
env:
  global:
  - REMOTEAPPDIR=/var/www/
  - REMOTEUSER=deploy
  - REMOTEHOST=46.101.164.17
  - PORT=80
install: yarn

script:
- yarn build
notifications:
  email: false
after_success:
- openssl aes-256-cbc -K $encrypted_7b417e6d3d7a_key -iv $encrypted_7b417e6d3d7a_iv -in deploy-key.enc -out deploy-key -d
- chmod 600 deploy-key && mv deploy-key ~/.ssh/id_rsa
- echo "deploy to 46.101.164.17"
- scp dist.tar.gz deploy@46.101.164.17:~/
- ssh deploy@46.101.164.17 'tar -xzvf ~/dist.tar.gz -C /var/www && cd /var/www && npm i --production && sudo npm run start &> /var/log/app.log'
