dist: trusty
language: node_js
node_js:
- 10.13.0
cache:
  directories:
  - node_modules
addons:
  sshknownhosts:
  - 46.101.164.17
branches:
  only:
  - master
env:
  global:
  - REMOTEAPPDIR=/var/www/
  - REMOTEUSER=deploy
  - REMOTEHOST=46.101.164.17
  - PORT=80
install: yarn
beforescript:
- chmod 600 deploy-key && mv deploy ~/.ssh/id_rsa
script:
- yarn build
notifications:
  email: false
after_success:
- echo "build done"
- scp dist.zip $REMOTE_USER@$REMOTE_HOST:$REMOTE_APP_DIR
- ssh $REMOTE_USER@$REMOTE_HOST 'unzip $REMOTE_APP_DIR/dist.zip'
before_install:
- openssl aes-256-cbc -K $encrypted_7b417e6d3d7a_key -iv $encrypted_7b417e6d3d7a_iv
  -in deploy-key.enc -out deploy-key -d
